#!/bin/bash

TRACKS="assets/tilemaped/tracks/final"
TILESSIZE=""

function make_track() {
	local FOLDER=$TRACKS/$1
	local TRACKNUM=${FOLDER:0-1}
	
	cp $FOLDER/tiles.bin DAT/TLST$TRACKNUM
	cp $FOLDER/map0.bin DAT/TRK$TRACKNUM
	cp $FOLDER/colmap0.bin DAT/CLM$TRACKNUM
	cp $FOLDER/pal.bin DAT/PAL$TRACKNUM

	./tools/waypoints tools/waypoint.t$TRACKNUM

	cp ./tools/waypoint.t$TRACKNUM.bin DAT/WAY$TRACKNUM

	TILESSIZE="$TILESSIZE $(get_tls DAT/TLST$TRACKNUM)"
}

function get_tls() {
	local TILES=$1
	echo $(/bin/ls -l $TILES | awk '{print $5}')
}

for t in $(ls $TRACKS)
do
	make_track $t
done

./tools/gameaddr $TILESSIZE

cp game.bin DAT/GAME
rm game.bin
